### ISSUE TITLE
Multiple Users - Client crash upon loading Galacticraft Entities

### ISSUE THREAD

**Issue by Firav** [TeamGalacticraft/Galacticraft-Legacy#100]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.3-Tekkit-2-Build

### Bug Details

Ported issue from xJon/The-1.12.2-Pack#828

**Basic details**

- Are you using a legitimate launcher and Minecraft account:
yes

- Are you using a computer with 8GB or more of RAM?
yes (varies per user)

- Are you using Java 8, 64-bit?
yes

**Information required**

- Is the modpack crashing: yes
- Crash/latest log:
I'll include the logs as they come to me:
https://mclo.gs/108GaQG
https://mclo.gs/BJY4mtE
https://mclo.gs/x9s1J7K
- Is Optifine installed or any other additional mods: no

**Describe the issue**

Multiple users are crashing upon loading entities from GalacticCraft. These players seem to leave the area and unload these entities, but when coming back to that area and the entities load again, crash ensues.

**Comment by ROMVoid95** [comment]
Can we check if the issue here is still present with the latest release?

**Comment by Firav** [comment]
@ROMVoid95 I no longer run the server that used this mod pack, which used this mod. I will not be able to test this issue for you.
