### ISSUE TITLE
Liquid in the Fluid Tank lost after server reloaded.

### ISSUE THREAD

**Issue by willis1030** [TeamGalacticraft/Galacticraft-Legacy#104]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.3 and lates 4.0.4

### Reproduction steps

1. stop the server
2. restart the server
3. all the liquid in the liquid tank lost. (tank empty)

**Comment by CHead2000** [comment]
Hey @ROMVoid95 , is there any chance I could pick this up? I'm new to contributing to open-source projects, but I'd love to give this one a try!

**Comment by ROMVoid95** [comment]
@CHead2000 absolutely, any and all help is always welcome here!

**Comment by CHead2000** [comment]
This should fix it. #109
