### ISSUE TITLE
Overlapping inventory tabs

### ISSUE THREAD

**Issue by Safeterror7** [TeamGalacticraft/Galacticraft-Legacy#108]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.4

### Log or Crash Report

there are two tabs in inventory that are overlapping one is the space equipment tab and another I don't know
![2022-11-22_21 49 31](https://user-images.githubusercontent.com/118868787/203461125-8c29989d-f0b7-4b1d-b402-04d51482114f.png)

### Reproduction steps

Idk

**Comment by ROMVoid95** [comment]
What other mods are loaded

**Comment by Safeterror7** [comment]
![unknown_2022 11 22-22 08_Moment](https://user-images.githubusercontent.com/118868787/203462493-83a2d8d7-98b2-49b1-91f4-036923d7d97f.jpg)

**Comment by Safeterror7** [comment]
forget that shortcut idk why thats in there

**Comment by ROMVoid95** [comment]
Modern warefare mod has known incompatibilities with Galacticraft.
