### ISSUE TITLE
(1.10.2) java.lang.NullPointerException: Unexpected error every time I teleport to asteroids with a mekanism teleporter

### ISSUE THREAD

**Issue by LittleTimmy52** [TeamGalacticraft/Galacticraft-Legacy#110]
### Forge Version

14.23.5.2860

### Galacticraft Version

whatever one space astronomy 2 uses (1.10.2)

### Log or Crash Report

[crash-2022-12-01_20.06.38-client.txt](https://github.com/TeamGalacticraft/Galacticraft-Legacy/files/10141006/crash-2022-12-01_20.06.38-client.txt)

### Reproduction steps

1. go to asteroids via tier 3 ship
2. make a mekanism teleporter
3. teleport home
4. teleport back
5. crash and receive error

**Comment by ROMVoid95** [comment]
The version used is severely outdated and will no longer receive any updates or fixes

**Comment by LittleTimmy52** [comment]
Well ok then
