### ISSUE TITLE
Server Crash on Pre-initialization 

### ISSUE THREAD

**Issue by AndraiNardo** [TeamGalacticraft/Galacticraft-Legacy#116]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.4

### Log or Crash Report

https://gist.github.com/MistikCodes/9c2fa7eaeb7878595068158aca80f257

### Reproduction steps

1. Download the mods listed above
2. Run a SH script using Magma server
3. Server refused to boot

**Comment by ROMVoid95** [comment]
reproduce the issue with a normal forge server without magma

**Comment by AndraiNardo** [comment]
seems to be that i was missing some key files in my server, it had nothing to do with your mod. thanks for your time anyways!
