### ISSUE TITLE
[Bug]: Player in survival mode can remove equipment with binding curse

### ISSUE THREAD

**Issue by HaHaWTH** [TeamGalacticraft/Galacticraft-Legacy#119]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.4

### Reproduction steps

1. In the Inventory interface of GalactiCraft
2. Then player can remove equipment with curse of binding

**Comment by MJRLegends** [comment]
Which equipment are you referring to here please?

**Comment by HaHaWTH** [comment]
Vanilla armor slot

**Comment by HaHaWTH** [comment]
> Which equipment are you referring to here please?
In vanilla armor slot,like this

https://user-images.githubusercontent.com/102713261/214473282-f451504e-b267-442e-87a8-e517528e5fa7.mp4

**Comment by ROMVoid95** [comment]
I don't really see this as a bug since that type of armor isn't meant for the slot anyway.

**Comment by HaHaWTH** [comment]
> I don't really see this as a bug since that type of armor isn't meant for the slot anyway.

Galacticraft always be in modpacks,i don't think armor in other mods is not meant and curse of binding enchantment is necessary for balance.so please fix it,thanks

**Comment by HaHaWTH** [comment]
> I don't really see this as a bug since that type of armor isn't meant for the slot anyway.

Galacticraft always be in modpacks,i don't think armor in other mods is not meant and curse of binding enchantment is necessary for balance.so please fix it,thanks❤

**Comment by HaHaWTH** [comment]
> I don't really see this as a bug since that type of armor isn't meant for the slot anyway.

Galacticraft always be in modpacks,i don't think armor in other mods is meaningless and curse of binding enchantment is necessary for the balance.so please fix it,thanks❤

**Comment by Klairm** [comment]
> > I don't really see this as a bug since that type of armor isn't meant for the slot anyway.
> 
> Galacticraft always be in modpacks,i don't think armor in other mods is meaningless and curse of binding enchantment is necessary for the balance.so please fix it,thanksheart

The fix should be included in the next release 👍
