### ISSUE TITLE
Server lag when charging Galacticraft machines

### ISSUE THREAD

**Issue by HaHaWTH** [TeamGalacticraft/Galacticraft-Legacy#120]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.4

### Reproduction steps

1. Connect the machine with electric generator by the Galacticraft cable
2. Server lags while charging the machine

**Comment by ROMVoid95** [comment]
Will need some supporting logs from your client or server if this is multiplayer.  99% of the time lag is cuased by misconfigured java arguments, Insuficient system resources/hardware, etc...

**Comment by HaHaWTH** [comment]
> Will need some supporting logs from your client or server if this is multiplayer. 99% of the time lag is cuased by misconfigured java arguments, Insuficient system resources/hardware, etc...

This issue also appears in singleplayer game,just connect the machine and charge it,internal server will lag,all JVM arguments are default,under JDK 8u351

**Comment by HaHaWTH** [comment]
> > Will need some supporting logs from your client or server if this is multiplayer. 99% of the time lag is cuased by misconfigured java arguments, Insuficient system resources/hardware, etc...
> 
> This issue also appears in singleplayer game,just connect the machine and charge it,internal server will lag,all JVM arguments are default,under JDK 8u351

CPU:Intel Core i5-12400F/AMD Athlon X2
8GB Memory Allocated

**Comment by ROMVoid95** [comment]
### *Will need some supporting logs from your client or server if this is multiplayer*

I took the liberty and ran the mod on the 3 computers in my office, with the lowest spec being an i5-2400 (an absolute relic) with profilers and no lag.

**Comment by HaHaWTH** [comment]
> ### _Will need some supporting logs from your client or server if this is multiplayer_
> I took the liberty and ran the mod on the 3 computers in my office, with the lowest spec being an i5-2400 (an absolute relic) with profilers and no lag.

I checked out the debug log and find VoxelMap may conflict with Galacticraft,after remove Voxelmap mod theres no lag anymore,sorry to bother you❤

**Comment by ROMVoid95** [comment]
> > ### _Will need some supporting logs from your client or server if this is multiplayer_
> > I took the liberty and ran the mod on the 3 computers in my office, with the lowest spec being an i5-2400 (an absolute relic) with profilers and no lag.
> 
> I checked out the debug log and find VoxelMap may conflict with Galacticraft,after remove Voxelmap mod theres no lag anymore,sorry to bother you❤

No worries, It's never a bother. Glad it was resolved.
