### ISSUE TITLE
Not really a bug but a problem[Bug]: 

### ISSUE THREAD

**Issue by MasterYoga6** [TeamGalacticraft/Galacticraft-Legacy#122]
### Forge Version

14.23.5.2846

### Galacticraft Version

any of the downloades

### Reproduction steps

When i try to enter  minecraft it says that I need forge 14.23.5.2847 but I have 14.23.5.2846 how can I bump my forge with this one number ?

**Comment by JunePrimavera** [comment]
Have you tried to install the new(er) version of forge?

**Comment by ROMVoid95** [comment]
[Use the installer for Forge](https://adfoc.us/serve/sitelinks/?id=271228&url=https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2857/forge-1.12.2-14.23.5.2857-installer.jar)

or if your using the Curseforge App, edit the instance and bump the version of forge.
