### ISSUE TITLE
[Bug]: Crash with TickCentral-3.2

### ISSUE THREAD

**Issue by Azazel0Sakura** [TeamGalacticraft/Galacticraft-Legacy#125]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.5

### Log or Crash Report

https://hastebin.com/share/isacorawoy.ruby

### Reproduction steps

1. Do this
2. Do that
3. Crash/Bug
...

**Comment by ROMVoid95** [comment]
Is this a modified RLCraft modpack?

**Comment by Azazel0Sakura** [comment]
Nope, made by my self with some mods from RLCraft.
