### ISSUE TITLE
[Bug]: Leaking fluid pipes

### ISSUE THREAD

**Issue by adamsong** [TeamGalacticraft/Galacticraft-Legacy#129]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.284

### Log or Crash Report

![image](https://user-images.githubusercontent.com/4607006/232952099-765af109-9bfa-4e7a-a331-7bb1efe20f2c.png)
![image](https://user-images.githubusercontent.com/4607006/232952682-284b1d9e-f106-4d1d-9f2c-c161809d8567.png)
![image](https://user-images.githubusercontent.com/4607006/232952715-0983c271-5d45-4ce4-8a97-8c6b74b312e8.png)
![image](https://user-images.githubusercontent.com/4607006/232972974-20d73917-94e6-4b7f-a797-86aa1f9b39c4.png)

### Reproduction steps

`TickHandlerServer.fluidNetworks` has 1640136 instances of `FluidNetwork` most of which only reference one `TileEntityFluidPipe`, with hundreds of thousands of tile entities with the same position. Ticking all of these causes massive amounts of server lag, solved by a restart.

My working theory is that unloading the chunk is supposed to delete the tile entity, but it doesn't get GC'd due to the reference from `TickHandlerServer.fluidNetworks` then the chunk gets loaded and creates a new tile entity, which makes a new network, which gets saved to the list. Its also possible that when the network is ticked, it loads the chunk, making the issue worse.

**Comment by ROMVoid95** [comment]
Can you iterate what you mean by leaking pipe please. Is this happening on every pipe system in your world? What are the coords in reference too in the attached screenshot? (if they are coords). I didn't write the network code and have tried to not touch as much of it as possible as its a sheer mind-f^&k to go through, and this issue is the first i've heard of seen of this. Also re-produce this on the most current version please to continue any further.

**Comment by adamsong** [comment]
> Can you iterate what you mean by leaking pipe please.

Memory leak, tile entities that minecraft has removed are being prevented from being cleared by hard references in galacticraft code

> What are the coords in reference too in the attached screenshot? (if they are coords). 

Coords are locations in which fluid pipe tile entities exist, the count is the number of tile entities with those coords. 

> and this issue is the first i've heard of seen of this

Likely the same bug as micdoodle8/Galacticraft#3448. This issue most likely will only affect players who don't restart every 24 or so hours, and have pipes they load and then unload, making it not noticeable, but almost certainly present.

> Also re-produce this on the most current version please to continue any further.

The [relevant line of code](https://github.com/TeamGalacticraft/Galacticraft-Legacy/blob/master-1.12/src/main/java/micdoodle8/mods/galacticraft/core/tick/TickHandlerServer.java#L95) has not been touched in 6 years.

**Comment by adamsong** [comment]
Bug still exists, not stale

**Comment by ROMVoid95** [comment]
@adamsong do you still have the world this happened in?

**Comment by adamsong** [comment]
I broke all the pipes that were causing issues
