### ISSUE TITLE
[Bug]: Gas Liquefier output to EnderIO Fluid Tank crashes

### ISSUE THREAD

**Issue by FuBangkun** [TeamGalacticraft/Galacticraft-Legacy#130]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.5

### Log or Crash Report

https://gist.github.com/FuBangkun/1a4de86b597e1119970db37b1135900e

### Reproduction steps

1. Place the EnderIO Fluid Tank on the Gas Liquefier output port of GalactiCraft
2. Set the direction of the Gas Liquefier output port to the input direction of the Fluid Tank
3. Crash

**Comment by Klairm** [comment]
I've managed to fix the crash by increasing the inventory size from 3 to 4 in the TileEntityGasLiquefier constructor, but the enderIO fluid tank will still not pull the fuel from the liquidtank for some reason

![imagen](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/40839469/70ce8a9f-14c3-4f9e-a034-4b9859296b23)

Edit: however, if you place a fluid pipe in the output of the gas liquefier then the EnderIO Fluid Tank will pull correctly the fuel
![imagen](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/40839469/6c2822d3-5242-4b01-9ab8-468d2c4d02ac)
