### ISSUE TITLE
[Feature]: Add Charcoal to acceptable Coal Generator input

### ISSUE THREAD

**Issue by LukeShortCloud** [TeamGalacticraft/Galacticraft-Legacy#131]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.280

### Reproduction steps

1. Place down a "Coal Generator".
2. Try using "Charcoal" to fuel it. It does not work.
3. Try using "Coal" to fuel it. It works.

The original Galacticraft mod [refused](https://github.com/micdoodle8/Galacticraft/issues/2091) to fix this bug because their goal was for people to use solar power instead. I believe that is invalid reasoning as charcoal and coal can be swapped out for each other in vanilla Minecraft and other various mods. It is also helpful for when there is no sun (especially on planets where it is mainly night time) and a player does not have an Energy Storage Module/Cluster to power a Fuel Loader to get back home.

**Comment by ROMVoid95** [comment]
I will add this into the mod, but charcoal will have a sugnificant reduction in power produced by it.

**Comment by ROMVoid95** [comment]
@LukeShortCloud 
Currently added in the most recent commit. Also handles OreDict enteries for coal and charcoal related items.
Example outputs from 1 of each:

**Charcoal Dust**
`113` gJ

**Coal Dust**
`4,320` gJ

**Charcoal Item**
`18,122` gJ

**Charcoal Block**
`375,867` gJ

**Comment by LukeShortCloud** [comment]
@ROMVoid95 Thank you, I appreciate your help implementing this feature and for the transparency on the power output values!
