### ISSUE TITLE
[Bug]: Crash server 1.12.2

### ISSUE THREAD

**Issue by gri3229** [TeamGalacticraft/Galacticraft-Legacy#132]
### Forge Version

14.23.5.2860

### Galacticraft Version

Galacticraft-1.12.2-4.0.5

### Log or Crash Report

[crash-2023-04-23_09.15.39-server.txt](https://github.com/TeamGalacticraft/Galacticraft-Legacy/files/11303043/crash-2023-04-23_09.15.39-server.txt)

https://gist.github.com/gri3229/9bb6e88a46c23fd7434281bc8e2223f3

### Reproduction steps

1. Installed Galacticraft-1.12.2-4.0.5 on the server
2. Judging by the crash report, the mod seems to be missing, but in fact it is
3. Crash/Bug
...

**Comment by ROMVoid95** [comment]
If the mod is in fact in the mods folder it should be loading, ensure you dont have any older versions of the mod in that folder as well. Closing this as i see nothing here that would point to an issue with the mod itself.
