### ISSUE TITLE
[Question] Why wasn't the repo transferred instead of forked and archived?

### ISSUE THREAD

**Issue by altrisi** [TeamGalacticraft/Galacticraft-Legacy#14]
Basically the question in the title.

Github allows transferring repositories from one account to another (or to an organization), keeping all history, issues, pull requests, stars, forks and even git/url relations working (Github creates proper redirections for absolutely everything).

Also, since this is a fork, this has currently less features than a "source" repository (most notably code search, it can't be used in a fork unless it has more stars than source repo, which isn't gonna be the case for many time).

You can find more information and documentation on how to transfer repositories on Github docs here: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/transferring-a-repository

If transferring now, you could transfer the current existing issues there, about commits, it seems there haven't really been many changes, except in some branches, that could be moved there first.

_Note: I've read the Contributing.md file, and yes, this may not apply to those, but I found more appropriate to report it here since it's directly related to the repo and, in some points of view, could be considered a bug/issue. I'm **not** going to transfer this to the forums though._

**Comment by craftablescience** [comment]
If it ever becomes a problem, there is a way to turn a fork into a base repository, by e-mailing GitHub.

**Comment by vos6434** [comment]
Micdoodle chose this as a lot of links lead to the original repo so we have chosen to fork instead of transfer.
Unless github will automatically redirect you to the new repo then we should transfer.

**Comment by altrisi** [comment]
Well, as mentioned in the first comment, Github will take care of redirecting every old link to the new repo when transferring. It is also kind-of mentioned in the document.

As an example, the known ModMenu mod for Fabric recently changed home from [Prospector/ModMenu](https://github.com/Prospector/ModMenu/) to an organization, [TerraformersMC/ModMenu](https://github.com/TerraformersMC/ModMenu), and all links and relations to the old repo automatically redirect to the new one. You can test that by getting to any (working) url in there and changing the organization name back to the old user name, you'll get redirected.

That works for any "sub"-link, including branches, commits, files, history, issues, PRs, configured git remotes, etc.

**Comment by v1993** [comment]
This is even more annoying now that this repo was moved to https://github.com/TeamGalacticraft/Galacticraft-Legacy/, so old links are kinda wrong.
