### ISSUE TITLE
[Feature]: Make Space Suits Armor configurable

### ISSUE THREAD

**Issue by HaHaWTH** [TeamGalacticraft/Galacticraft-Legacy#140]
### Searched For Existing Request?

Yes I Have

### Feature Description

I installed GalactiCraft on my server, it was really an amazing mod, but I found that the armor   count of the spacesuit is too high, just wearing a tier-1 spacesuit can block most of the physical damage. Making this configurable is necessary and server owners really need it🙏

**Comment by ROMVoid95** [comment]
I'd be more than happy to accommodate, however GC itself doesn't have any Space Suit armor. only items that are placed into gc's own player tab (being the oxygen gear and iso/thermal outfits). I have a feeling your talking about the Space Suits from Extra Planets addon?

**Comment by HaHaWTH** [comment]
Ah, I made a mistake, sorry about that, should I goto MJRLegends‘ repository and submit this issue?
