### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by onyxagata** [TeamGalacticraft/Galacticraft-Legacy#141]
### Forge Version

14.23.5.2859

### Galacticraft Version

4.0.5

### Log or Crash Report

Unable to launch to, or /dimensiontp to Asteroids, Moon, or Mars

I believe it can be relate to this issue: https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues/92

My text is green tho, instead of red.

### Reproduction steps

1. Do this
2. Do that
3. Crash/Bug
...

**Comment by onyxagata** [comment]
Log: https://mclo.gs/lhVXHBw

**Comment by onyxagata** [comment]
I will send a screenshot later

**Comment by ROMVoid95** [comment]
create a proper issue using the template provided and also provide a proper log and any other information needed.
