### ISSUE TITLE
[Bug]: Not able to travel to Moon, Asteroids, and Mars 

### ISSUE THREAD

**Issue by onyxagata** [TeamGalacticraft/Galacticraft-Legacy#142]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.5

### Log or Crash Report

https://paste.gg/p/anonymous/bcac5a89dcf84c379eee030d96f9c525

### Reproduction steps

1. Open galaxy map
2. Click moon/asteroids/ mars
3. Unable to transport to moon/asteroids/mars
...

**Comment by onyxagata** [comment]
Client log: https://mclo.gs/mKnHggE

**Comment by onyxagata** [comment]
Unable to launch to, or /dimensiontp to Asteroids, Moon, or Mars. Using a custom modpack using Galacticraft and Extra Planets, I don't have a problem with any Extra Planets worlds

I believe it could be relate to this issue: #92

My text is green tho, instead of red, indicating I should be able to travel to it

**Comment by onyxagata** [comment]
![2023-06-17_10 33 45](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/56618954/06867e6f-289f-4a3a-97ce-b4138d64a011)

**Comment by ROMVoid95** [comment]
The client log is indicating it cannot find dimension -28, can you provide the galacticraft config files please

**Comment by TheMCSpacePro** [comment]
Also, does this occur with Galacticraft on its own? Might be another mod conflicting with GC.

**Comment by MJRLegends** [comment]
This issue is caused by mocreatures mod. it's a known issue.

**Comment by TheAvantianGod** [comment]
> This issue is caused by mocreatures mod. it's a known issue.

whats the fix I'm having the exact same problem

**Comment by MJRLegends** [comment]
@TheAvantianGod Sadly removal of mocreatures mod seems to fix this issue. Please do reach out to the mocreatures mod dev tho to see if they can do anything for you. 

Personally im a dev of ExtraPlanets addon, and i cant see for the life of me how a mob related mod causes this, but sometimes the weirdest issues are just a result of a feature in a certain use case.

**Comment by TheAvantianGod** [comment]
@MJRLegends I gone travelled to all the planets on a different save in creative and i was able to go to every dimension but different planets lead me to different planets i made a note file here. Is that still to due with mocreatures? 

mercury - mercury
venus - triton
overworld - overworld
mars - asteroids
	phobos - Callisto
	deimos - phobos
asteroids - venus
ceres - ceres
jupiter - jupiter
	Io - Deimos
	Europa - Io
	Ganymede - Rhea
	Callisto - Ganymede
Saturn - Saturn
	Rhea - Titan
	Titan - Oberon
	Iapetus - Moon
Neptune - Pluto
	Triton - Europa
Pluto - Eris
Eris - Kepler22b
kepler 22b - Mars

**Comment by MJRLegends** [comment]
That seems to be the same issue yea
