### ISSUE TITLE
[Bug]: Caused by: java.lang.NoSuchFieldError: SATELLITE

### ISSUE THREAD

**Issue by lp20010415** [TeamGalacticraft/Galacticraft-Legacy#143]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.5

### Log or Crash Report

https://gist.github.com/lp20010415/814364a78bec498950c73cbfd12b4c97

### Reproduction steps

after update galaxy run game get bug.

**Comment by ROMVoid95** [comment]
Not a galacticraft issue, but update AsmodeusCore to the latest version.

**Comment by lp20010415** [comment]
> Not a galacticraft issue, but update AsmodeusCore to the latest version.

All right, before i think download one, actually also need this? And other needed?
