### ISSUE TITLE
[Bug]: Random Crash in Overworld - Client Side

### ISSUE THREAD

**Issue by whatsapp2** [TeamGalacticraft/Galacticraft-Legacy#146]
### Forge Version

14.23.5.2860

### Galacticraft Version

1.12.2-4.0.5

### Log or Crash Report

https://gist.github.com/whatsapp2/154c07d87fcf43d1047e94f7814ed026

### Reproduction steps

For a bit of context, I've been playing in a private server with some friends. Could give server specifications if needed, but I don't think the server is the main problem with this crash.
The day the crash happened, we updated 3 mods: 
- HBM Nuclear Tech Mod Extended Edition (Also known as Alcater Version): `1.12.2-1.9.7`, 
- Weather2 Remastered:`1.12.2-2.8.8-indev` 
- Gregica++: `0.4.4-alpha-hotfix` 

The crash randomly happen when I was building in the overworld, while my friend was in a nuclear wasteland dimension from NC:O (NuclearCraft:Overhauled).

**Comment by ROMVoid95** [comment]
want to keep this open until fix is verified
