### ISSUE TITLE
[Bug]: Caught a weird crash from Galacticraft/Galacticraft Planets

### ISSUE THREAD

**Issue by X-XLebyshek** [TeamGalacticraft/Galacticraft-Legacy#148]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.5

### Log or Crash Report

https://gist.github.com/X-XLebyshek/003e637746f5905e37776e5cd25d0dbf

### Reproduction steps

I just launch Minecraft with some mods (yeah, like 486) and recieve this crash. I didn't find any helpful info about this error, they say it's rare.

**Comment by TheMCSpacePro** [comment]
Question: Does this occur with JUST Galacticraft? If not, is it possible to find the combo of mods that cause this? My bet is on **Phosphor**, but it could be anything.

**Comment by Klairm** [comment]
Which language are you using?

**Comment by TheMCSpacePro** [comment]
According to the crash log, they are using American English, or as the game calls it, "English (US)".

**Comment by DJEscHGL** [comment]
Hi, I have the same problem. 
https://gist.github.com/DJEscHGL/f74ade76b84da471f1d2f35429e65f77
Language of win11 - English US, but for my friends with other language of system works fine.
Can you please provide .jar file with fix?

**Comment by ROMVoid95** [comment]
> 

The fix will be in the next release

**Comment by Dermix121** [comment]
I have the same problem 
I dont use any other mod and its just crashes
