### ISSUE TITLE
[Bug]: Returning to Overworld requires only Tier 1 Rocket from any planet

### ISSUE THREAD

**Issue by FuBangkun** [TeamGalacticraft/Galacticraft-Legacy#150]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.5

### Reproduction steps

Players to return to the Overworld from any planet using just a Tier 1 Rocket. It should be because that the calculation for the required rocket tier to reach each planet is based on Earth, rather than being relative to the planet from which the rocket was launched.

**Comment by TheMCSpacePro** [comment]
Addons like Asmodeus Core already fix this.
