### ISSUE TITLE
[Bug]: Crash on launch

### ISSUE THREAD

**Issue by Dermix121** [TeamGalacticraft/Galacticraft-Legacy#152]
### Forge Version

14.23.5.2860

### Galacticraft Version

Galacticraft-1.12.2-4.0.5

### Log or Crash Report

https://hastebin.com/share/uhoroqufip.php

### Reproduction steps

1. Do this
2. Do that
3. Crash/Bug
...
You ust launch it

**Comment by TheMCSpacePro** [comment]
This seems like the same general thing as #148
The crash reports even share the error itself: 
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft (galacticraftcore)   Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 3

**Comment by TheMCSpacePro** [comment]
Found something showing this is on a cracked launcher: a mod called "tlauncher_custom_cape_skin".

**Comment by Dermix121** [comment]
And what about it?

**Comment by ROMVoid95** [comment]
@Dermix121 No support for cracked account or clients

**Comment by Dermix121** [comment]
And why?
Just you to know my Non crarcked accont get stolen and i dont want and wont to pay the same game twice
And do you have any problem whit those how dont want to spend on games whit out a physical value or what?
And if you have problem with that than your mindset is kinda outdate and i refuse to belevi that you don't play any game cracked version even in your childehood

**Comment by JunePrimavera** [comment]
If your account was stolen, contact Mojang for them to sort it out.

Piracy is piracy, it's understandable as to why it's not supported here.

**Comment by Dermix121** [comment]
i can fuck my sefl with them when I tried, they said that your account is your own responsibility

**Comment by Dermix121** [comment]
I tried but with no result

And if you have problem with Piracy in this case than your mindset is kinda outdated and i refuse to believe that you don't play any game cracked version even in your childhood

**Comment by JunePrimavera** [comment]
I believe it's immoral but yes, most people have in the past. It's also illegal in most of the world, hence, no support.

No support means no support, no need to start an argument here.
