### ISSUE TITLE
[Bug]: Basic Solar Panel Awards Both Solar Panel Advancements

### ISSUE THREAD

**Issue by TheMCSpacePro** [TeamGalacticraft/Galacticraft-Legacy#154]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.5

### Log or Crash Report

https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/53196852/da6c6619-158b-4725-aeff-9b59efee479b

Since there's no log (no crash ever happens), I'll just provide a video showing the bug happening on my end instead.

### Reproduction steps

1. Obtain a Basic Solar Panel
2. Realize you just got the advancements for both the Basic _**AND**_ Advanced Solar Panel simply for having the Basic one.
...

**Comment by TheMCSpacePro** [comment]
Had to edit it to fix a grammar mistake.

**Comment by JunePrimavera** [comment]
Even if there's no crash, there should still be a log (logs/latest.log is always generated)

**Comment by TheMCSpacePro** [comment]
Looks like 4.0.6 fixes this, so closing the issue.
