### ISSUE TITLE
[Bug]: Standard earth gravity and dimension handling on GC planets/moons

### ISSUE THREAD

**Issue by MrFuzzihead** [TeamGalacticraft/Galacticraft-Legacy#155]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.5

### Log or Crash Report

https://gist.github.com/MrFuzzihead/72cf03b47bb7d60766cd877cfab98822

Mod list: https://gist.github.com/MrFuzzihead/e1b6cdacdb4171964d2ba9311391917b

### Reproduction steps

1. Load GC dimension
2. Have all GC equipment, extraplanets suit as well
3. Earth gravity rather than planet/moon/station gravity
...

**Comment by TheMCSpacePro** [comment]
Does Extra Planets have suit modules? Wondering if this is **intended behavior** on Extra Planet's end.

**Comment by TheMCSpacePro** [comment]
Also, GC 4.0.6 is out.

**Comment by MrFuzzihead** [comment]
AFAIK this is unrelated to extra planets, tested with ExtraPlanets config set to legacy gravity and extraplanets gravity, and with and without space suits. I will try to test with the new version, however this has been an issue I've seen for around 2 years and the new version doesn't appear to fix this in the changelist, so we'll see

**Comment by MrFuzzihead** [comment]
Officially tested without extra planets and the gravity issue goes away. I'll consider this fully on their mod then and close this one out!
