### ISSUE TITLE
[Bug]: Crash when changing keybinds

### ISSUE THREAD

**Issue by xJon** [TeamGalacticraft/Galacticraft-Legacy#157]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.6-snapshot-10

### Log or Crash Report

https://mclo.gs/4j1V2o3

### Reproduction steps

Not too certain, as the issue was reported by players in random places.

> I wanted to change the buttons, but the game crashed and I can't restart it.

**Comment by ROMVoid95** [comment]
Can we get the key that was pressed that caused the crashes? It may possibly be a key they bound to another key other than the default

**Comment by xJon** [comment]
Unfortunately not at the moment, but if the issue is reported by another player I'll ask for more information.

**Comment by xJon** [comment]
Pretty sure this was a duplicate of https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues/181.
