### ISSUE TITLE
[Bug]: missing item for modObject

### ISSUE THREAD

**Issue by AceSardonyx** [TeamGalacticraft/Galacticraft-Legacy#164]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.6

### Log or Crash Report

https://gist.github.com/AceSardonyx/83ee3cdd9d2aa61a13af49cd177b583c

### Reproduction steps

1. launch the game
2. go to the moon, at least that is what I did

**Comment by ROMVoid95** [comment]
where did you obtain the Galacticraft file

**Comment by AceSardonyx** [comment]
I meant to use version 4.0.6 but I got it from curseforge

**Comment by AceSardonyx** [comment]
I downloaded a newer version from modrinth (I love modrinth)
New log: https://mclo.gs/WFKU387
Same error pretty sure ya

**Comment by ROMVoid95** [comment]
From what has been provided this error is from enderio and not thrown by anything in Galacticraft.
