### ISSUE TITLE
[Bug]: Crash caused by "Exception in server tick loop" 10 seconds after opening a world with mods installed 

### ISSUE THREAD

**Issue by Lupa13** [TeamGalacticraft/Galacticraft-Legacy#171]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.3

### Log or Crash Report

https://gist.github.com/Lupa13/dbcfb8f73b6d79d8327081f9341b1f53

### Reproduction steps

1. I try to open a world with mods installed (including Galacticraft and other mods). The world startup completes successfully
2. When I enter the world, I can only see the sky and rain falling. I also hear some strange noise repeated very quickly (as if there was some automatic farm working near the spawn point trying to load). After less than 15 seconds the animations freeze and the game crashes
3. I have a copy of the same world in creative mode, with the same Minecraft version and mods installed and it never crashes
4. I recently increased my PC's RAM from 8GB to 32GB and I allocated 18GB to Minecraft (I thought it didn't have enough memory to load the mods and that specific world) but there was no change in the game

**Comment by ROMVoid95** [comment]
Try with the latest version, if the issue is the same as the provided crash-report, also upload the latest.log file.

**Comment by Lupa13** [comment]
I installed Galacticraft 4.0.6 and opened the world again but the game still crashes, with the same error message.
Here's the latest.log file.
Thank you
[latest.log](https://github.com/TeamGalacticraft/Galacticraft-Legacy/files/13336446/latest.log)

**Comment by marcus8448** [comment]
It looks like MusicCraft is causing the crash - try without it.

**Comment by Lupa13** [comment]
It works now, thank you so much @marcus8448 and @ROMVoid95 for your help!!
