### ISSUE TITLE
[Bug]: Game Stuck on Loading Screen

### ISSUE THREAD

**Issue by tmdakm** [TeamGalacticraft/Galacticraft-Legacy#173]
### Forge Version

14.23.5.2847

### Galacticraft Version

4.0.2.281

### Log or Crash Report

https://paste.gg/p/anonymous/1d081d2337f6429ca3a1dae057468928

### Reproduction steps

No another mod about Galacticraft

我第一次发射火箭到空间站，随后显示关闭内置服务端，然后卡在"Prepare to Entry"界面。
我强制关闭游戏并重新尝试（空间站应该建立成功，但是由于某种原因我的星图界面特别小）发射到地球，然后卡在了“Taking one giant leap”界面。(当我尝试发射到月球时也一样）
I launched a rocket to the space station for the first time, and then it showed that the built-in server was closed, and it got stuck on the "Prepare to Entry" interface.

I forcibly closed the game and tried again (the space station should have been successfully established, but for some reason my star map interface was very small) to launch to Earth, and then got stuck in the "Taking one giant leap" interface.(when i trying get to the Moon, it's still stuck in the "Taking one giant leap" interface.)
![image](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/96684075/d551a301-639f-47e6-86ad-e4eb339b298f)
here's mod list
![image](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/96684075/364fb686-fc28-4844-afc8-5d8a6da45e64)
![image](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/96684075/a19f6c0b-64f8-46eb-a113-dac987eb12e5)
![image](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/96684075/8b078c64-60f1-46c5-a750-1845de651d1e)

**Comment by tmdakm** [comment]
When I join this world, it will show star-map, and i go to any planets, it will stuck

**Comment by tmdakm** [comment]
I think this is the error log.
![image](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/96684075/e8d7d438-fc12-46c7-9e0a-018cee5ee529)

**Comment by ROMVoid95** [comment]
Your using an unsupported version of Galacticraft (the .281 version was even removed from the downloads due to a critical error)
please use the latest version. 

[curseforge](https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy/files/4665385) or [modrinth](https://modrinth.com/mod/galacticraft-legacy/version/4.0.6)
