### ISSUE TITLE
[Bug]: Dungeons not generating at all

### ISSUE THREAD

**Issue by Def-Try** [TeamGalacticraft/Galacticraft-Legacy#179]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.281

### Description

Dungeons are not generating at all. Every planet that i expect to have dungeons just does not generate them.
Dungeon locator is just pointing down all the time.

### Log or Crash Report

https://gist.github.com/Def-Try/5224953af4a574b5233ae418f0f02ff4

### Reproduction steps

1. Acquire everything needed to go to space
2. Go to space, any planet, search for dungeons
3. Look inside
4. No dungeons

### Installed addons

- Galaxy Space

### Game type

- MP, with SpongeForge 2838-7.4.7

**Comment by Def-Try** [comment]
Uninstalling GalaxySpace had no effect, and deleting SpongeForge (seemingly) corrupts world in a way that makes it unjoinable

**Comment by IO2I** [comment]
Pretty sure that's a known issue with 281. Try downloading that latest version of GClegacy from curseforge or modrinth

**Comment by Def-Try** [comment]
I **think** 281 worked okay before, but i'll try 280 anyways.

**Comment by IO2I** [comment]
Are you not able to use this?
https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy

**Comment by IO2I** [comment]
Are you not able to use this?
https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy
