### ISSUE TITLE
Precision loss in terrain generation due to floats

### ISSUE THREAD

**Issue by muzikbike** [TeamGalacticraft/Galacticraft-Legacy#18]
Minecraft version: 1.12.2
Galacticraft version: 281

Single player (SP)

Any Galacticraft add-ons installed? Please list all of them: Yes and no; issue can be reproduced in both base galacticraft with no other mods and with addons which use the same terrain generator for other planets

Please provide screenshots / videos / full modlist as needed

Please state the site that you downloaded Galacticraft from: micdoodle site

It seems as though the terrain generator used for the moon/mars uses floats for some reason, rather than integers or a double. This isn't much of an issue at the exact center of the world, bu tteleporting out far enough results in prominent artifacts in terrain generation, resulting in terrain becoming far more blocky than it should be.

![2021-01-31_07 56 38](https://user-images.githubusercontent.com/52297970/106378226-016e0400-639b-11eb-8ca8-a7a6e48627cd.png)
![2021-01-31_07 56 58](https://user-images.githubusercontent.com/52297970/106378227-029f3100-639b-11eb-9682-d43bc6c2785f.png)
![2021-01-31_07 58 26](https://user-images.githubusercontent.com/52297970/106378229-0337c780-639b-11eb-8cb2-b155a9afd93f.png)
![2021-01-31_07 58 31](https://user-images.githubusercontent.com/52297970/106378231-03d05e00-639b-11eb-9215-a7121131d68f.png)
![2021-01-31_07 58 54](https://user-images.githubusercontent.com/52297970/106378233-0468f480-639b-11eb-9a6a-623ae6da063f.png)

Since blocks can only exist on integer coordinates, I don't see the point in using a float - vanilla's dimensions as well as Venus all use integers for their terrain generators and do not have this issue.

**Comment by ROMVoid95** [comment]
they use floats for the [Gradient](https://github.com/TeamGalacticraft/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/perlin/generator/Gradient.java) style generation.

**Comment by v1993** [comment]
If it's an issue with floats and integers can't be used, would using doubles instead provide enough precision for all valid world chunk?

**Comment by ROMVoid95** [comment]
> If it's an issue with floats and integers can't be used, would using doubles instead provide enough precision for all valid world chunks?

Honestly, will need to look into it further. doubles do provide a higher precision (approx. 2x) but I wouldn't be able to say it would change anything.

**Comment by ROMVoid95** [comment]
@muzikbike See if this can be reproduced with the builds in `mods.zip`

[mods.zip](https://github.com/TeamGalacticraft/Galacticraft/files/5974578/mods.zip)

**Comment by muzikbike** [comment]
Confirmed fixed with the provided builds.

**Comment by ROMVoid95** [comment]
Fixed in latest commit
