### ISSUE TITLE
[Feature]: mod info

### ISSUE THREAD

**Issue by Ironarc-corp** [TeamGalacticraft/Galacticraft-Legacy#180]
### Searched For Existing Request?

No

### Feature Description

I would like to know I know the mod well but on the last mod pack it is no longer there I would like to know if there will soon be version 1.20 or the mod will definitely remain in 1.12

**Comment by SebaSphere** [comment]
Galacticraft is being rewritten on 1.20 Fabric, which you can monitor progress at https://github.com/TeamGalacticraft/Galacticraft (alongside an attached Discord server in the GitHub) 🙂

**Comment by Ironarc-corp** [comment]
ha rewriting totally ok and the discord links don't work
