### ISSUE TITLE
[Bug]: Changing sneak keybinding crashes game 

### ISSUE THREAD

**Issue by Timothylul** [TeamGalacticraft/Galacticraft-Legacy#181]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.6

### Log or Crash Report

https://mclo.gs/JKyKJpb

### Reproduction steps

1. Change the sneak key to < (QWERTZ keyboard layout).
2. Game instantly crashes

**Comment by ACGaming** [comment]
Using GameSettings instead of the LWJGL Keyboard class should help in this case.
