### ISSUE TITLE
[Bug]: crash with water electrolyzer(GC) and pressurized pipes(Mekanism)

### ISSUE THREAD

**Issue by YiceLi** [TeamGalacticraft/Galacticraft-Legacy#186]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.4

### Log or Crash Report

https://gist.github.com/YiceLi/7826c22492de1eaa6a55fdbe3cff4611#file-crash_report-txt

### Reproduction steps

1. Do this
2. Do that
3. Crash/Bug
...
1.Place the water electrolyzer of the GC mod
2.connect with any pressurized pipe of the Mekanism mod (including oxygen and hydrogen outlets)
3.then the game crashes and the save is corrupted

**Comment by TheMCSpacePro** [comment]
Pretty sure this was fixed in 4.0.5.
