### ISSUE TITLE
[IMPORTANT]: Ideas for Galacticraft

### ISSUE THREAD

**Issue by reverentfeynmen** [TeamGalacticraft/Galacticraft-Legacy#194]
### Searched For Existing Request?

Yes I Have

### Feature Description

...
I LOVE Galacticraft. And here are some ideas to make it better.

Remove the dungeons. Or atleast add config option to remove them.
Add better worldgen.
Make the API easer to mod with.
In place of the dungeons. Add ability to find Rocket schematics inside crashed probes.
Add unlimited rocket movement.
Make the rocket actually fly through space rather then just winding up there/teleportation.
For combat. Add alien bases to the Planets. And add a Laser Gun or Plasma Sword/stuff that's not just vanilla.
Add a warp drive to Space Ships.
Add a render Celestial Body for all Planets and not just Earth.
Add Jupiter and the other Gas Giants but not with a solid surface/all gases and liquids.
Add a Space Station for each Planet including unrealized Planets.
Add abilitiy to create Space Stations on Moons.
Add ability to craft your own Rocket not just Tier 2 Tier 3 or Tier 1/remove all NASA Workbench limits.
Add the ability to easely create a new Planet on Galaxy Map just like you can with Space Stations/click on Sun and click create new Planet.
Create a 1.16 Forge port of Galacticraft Legacy.
Add stars and Galaxies backround to the Galaxy Map.
Remove that creepy dungeon sound.
Change Rocket Texture.
Add ambient Space sounds.

### Screenshots and Videos

![Screenshot 2024-03-09 220728](https://github.com/TeamGalacticraft/Galacticraft-Legacy/assets/166317640/da2fd654-35bd-4ec6-9eea-1835684dd94b)

### Additional Context

These ideas could even be used for educational purposes about Space Exploration. And would really improve emersion a lot.

**Comment by reverentfeynmen** [comment]
Tell the Galacticraft 5 Development Team to rethink adding dungeons to Galacticraft 5.

**Comment by reverentfeynmen** [comment]
Note For TeamGalacticraft. The GC dungeons were just a Mojang EULA Script. Don't follow it!

**Comment by ROMVoid95** [comment]
why is this here?
