### ISSUE TITLE
(1.12.2) Server/Singleplayer huge bugs with Galacticraft planets and moons

### ISSUE THREAD

**Issue by Migmag789** [TeamGalacticraft/Galacticraft-Legacy#34]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:
Galacticraft version ("latest" is not a valid option): GalacticraftCore/Planets/MicDoodleCore 1.12.2-4.0.2.280

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)?
- Both Singleplayer and Multiplayer, doesn't have Sponge

Any Galacticraft add-ons installed? Please list all of them: ExtraPlanets (the bugs still occurs without the addon, I tested it and I actually reported the issue to the addon first)

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site: No crash reports

Please provide screenshots / videos / full modlist as needed
https://pastebin.com/4VYqGp5f

Please state the site that you downloaded Galacticraft from: The official site : https://micdoodle8.com/mods/galacticraft/downloads

The issue: When going on the moon (or anywhere which is added by GC or EP), my computer (and any computer of any player in any GC/EP dimension) starts consuming a ton of resources, ram, gpu and more, also there is earth gravity in all planets, chunks generate hardly, the server is lagging a lot, the TPS are greatly going down, oxygen/pressure/radiation bars don't even show up. The issue is still here even when ExtraPlanets is not. I hope the problem is easily fixable, and thanks to all of the team for this great mod!

**Comment by ROMVoid95** [comment]
can you provide any logs? they will contain some needed information like java arguments, log outputs, and if the specs of the pc / vps running the game (or server) can be provided that would help as well.

**Comment by Migmag789** [comment]
Hi, because of another mod, the logs are spammed of informations. I can give you the JVM arguments, the specs of my computer, of the server and maybe some other player's PC specs.
My own JVM arguments : (there are none)
Servers' JVM arguments : -Dfml.readTimeout=1000
My specs : 16GB RAM, ADM Ryzen 3 3100 4-Core Processor 3.59GHz
Server specs : I can't access them but I know there is a SSD and 8GB of RAM (my offer is BisectHosting's Premium Minecraft Hosting - 8GB)
Some other players have very good computers and the lags are not supposed to happen (I've played bigger modpacks, even with Galacticraft).
For the other issues I've listed, I don't really know and I forgot to mention there are vanilla clouds in the sky of the moon (haven't checked other planets).
Thank you!

**Comment by ROMVoid95** [comment]
this doesn't tell me anything, if the logs are too long, you can post what you can to a pastebin site and provide the link. Every server will have more arguments than that. and so will your client. The logs will provide this information. Other than that, seems like this is mod conflicting issues, unoptimized configurations, Inadequate hardware resources, or client issues.

**Comment by Migmag789** [comment]
https://www.mediafire.com/file/6efdpmh3wd72rpg/2021-08-07-1.log.gz/file
The log file is 2.8GB long, so I uploaded the log on mediafre. The thing is that I launch the pack with Curseforge, if you want my MC launcher arguments there they are: -Xmx11136m -Xms256m -XX:PermSize=256m -Dminecraft.applet.TargetDirectory="C:\Users\Migmag\Documents\Twitch\Minecraft\Instances\Guangxi 2" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US

For the server, I don't really know, and I don't think the server arguments are even influencing the problem as it also happens in singleplayer. The performance problem isn't even the most concerning, all of the others problems I talked about are not supposed to happen and are due to something, maybe another mod, but I have to find which one and I can't do that alone, even more if Galacticraft dimensions is the only "victim" of the issue, that's why I'm reporting the problem, because I may not be the only one to have that issue. It can't be because of my computer or the server, it happened even to the people with the biggest computers (it goes up to 18GB of RAM being consumed). I hope there's a way to find what is causing all of that turmoil. Thank you for understanding!

**Comment by Migmag789** [comment]
A friend told me where the issue came from, and the result was surprising, for sure: the mod responsible for this was Universal Remote. I don't know how or why, but I guess that's how it is. I'm really sorry for bothering all of you and I hope you'll all have a great day, thanks for this amazing mod!
