### ISSUE TITLE
Infinite Oxygen gets used and loses durability for some reason

### ISSUE THREAD

**Issue by NotAstralYT** [TeamGalacticraft/Galacticraft-Legacy#41]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.280

### Log or Crash Report

not crashing

### Reproduction steps

1. Do this
2. Do that
3. Crash/Bug
...
1. make a creative world then get a infinite oxygen 
2. use it on another planet
3.
![2022-01-20_17 37 27](https://user-images.githubusercontent.com/96470356/150312875-fa4a6ac4-52cf-49d4-83e8-962e9b1ec377.png)

**Comment by ROMVoid95** [comment]
can you paste your modlist on pastebin/gist.github and provide the link?

you can get an easy to read modlist by forcing a crash in-game holding F3+C for 6-8 seconds then use the modlist table from that report file.
