### ISSUE TITLE
CustomNPCs mod crashes GC 283 during game launch

### ISSUE THREAD

**Issue by EzerArch** [TeamGalacticraft/Galacticraft-Legacy#43]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.283

### Log or Crash Report

https://gist.github.com/EzerArch/a873268c761a310ef12aca9e19ad8f37

### Reproduction steps

GC 283 will crash with CustomNPCs 1.12.2 during launch, while GC 280 didn't. Probably GC inventory is conflicting with CustomNPCs'. 

With a fresh instance, start the game with these mods in mod folder:
* CustomNPCs_1.12.2-(05Jul20).jar
* Galacticraft-1.12.2-4.0.2.283.jar
* OptiFine_1.12.2_HD_U_G5.jar (optional, it doesn't change the result)

The launch will break at "Loading - Constructing mods" with:
```
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/client/tabs/InventoryTabFactions
Exit Code: -1
```

**Comment by MJRLegends** [comment]
Yea because things were changed without much consideration most things that had compact are now broken :(

**Comment by craftablescience** [comment]
@MJRLegends rom went to a lot of trouble to ensure compatibility, sorry you feel differently
anyway this isn't entirely relevant to the issue

**Comment by ROMVoid95** [comment]
@MJRLegends what was released has zero, and I do mean zero, breaking changes nor major changes that wouldn't be considered breaking. Your comment also does not even attempt to help or offer any insight. 

@EzerArch thanks for this, I'll get the fix uploaded tonight.

**Comment by MJRLegends** [comment]
You're correct i would like to apologise for my previous message :)

**Comment by ROMVoid95** [comment]
No worries/animosity here 👍

**Comment by EzerArch** [comment]
> @EzerArch thanks for this, I'll get the fix uploaded tonight.

Thank you @ROMVoid95 . :)

**Comment by ROMVoid95** [comment]
So the cause for this crash is a tad tricky. The root cause is due to CustomNPC's containing classes in `micdoodle8.mods.galacticraft.api.client.tabs`. Since the new release is signed these conflict with the classes in the package under CustomNPC's jar.

**Comment by ROMVoid95** [comment]
In the end the quickest fix is to just remove jar signing and fingerprints. Going through the issue reporting process for CustomNPC's and having to wait on an update (if they would) isn't at the moment a priority for the sake of having GC signed.
