### ISSUE TITLE
crash when importing hydrogen into methanesynthesizer with mekanism gastank

### ISSUE THREAD

**Issue by Gitcrafter** [TeamGalacticraft/Galacticraft-Legacy#50]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.284

### Log or Crash Report

https://gist.github.com/Gitcrafter/8a30aa540b91f5059dceec0f70522bdc

### Reproduction steps

1. place a Methanesynthesizer into the world
2. place a Mekanism-Gastank containing Hydrogen on the left side of the synthesizer
3. set the Gastank to export the Hydrogen into the synthesizer and see the game crash

**Comment by ROMVoid95** [comment]
does the crash occur if the gas tank is attached to the synthesizer via pressurized pipe?

**Comment by Gitcrafter** [comment]
I didn´t tested it with a pipe, only with a gas tank, that is attached **directly** to the synthesizer

**Comment by Gitcrafter** [comment]
I tested it with a pressurized pipe and it crashed as soon as I placed the pipe next to the synthesizer, even without the gas tank giving me this crash with only Galacticraft and Mekanism:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.2.284.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 2/21/22 8:27 PM
Description: Ticking block entity

java.lang.ClassCastException: micdoodle8.mods.galacticraft.planets.mars.tile.TileEntityMethaneSynthesizer cannot be cast to mekanism.api.gas.IGasHandler
	at mekanism.common.util.GasUtils.lambda$getConnectedAcceptors$0(GasUtils.java:32)
	at mekanism.common.util.GasUtils$$Lambda$482/394864597.accept(Unknown Source)
	at mekanism.common.util.EmitUtils.forEachSide(EmitUtils.java:97)
	at mekanism.common.util.GasUtils.getConnectedAcceptors(GasUtils.java:31)
	at mekanism.common.util.GasUtils.getConnectedAcceptors(GasUtils.java:42)
	at mekanism.common.tile.transmitter.TileEntityPressurizedTube.func_73660_a(TileEntityPressurizedTube.java:80)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mekanism.common.util.GasUtils.lambda$getConnectedAcceptors$0(GasUtils.java:32)
	at mekanism.common.util.GasUtils$$Lambda$482/394864597.accept(Unknown Source)
	at mekanism.common.util.EmitUtils.forEachSide(EmitUtils.java:97)
	at mekanism.common.util.GasUtils.getConnectedAcceptors(GasUtils.java:31)
	at mekanism.common.util.GasUtils.getConnectedAcceptors(GasUtils.java:42)
	at mekanism.common.tile.transmitter.TileEntityPressurizedTube.func_73660_a(TileEntityPressurizedTube.java:80)

-- Block entity being ticked --
Details:
	Name: mekanism:pressurized_tube // mekanism.common.tile.transmitter.TileEntityPressurizedTube
	Block type: ID #364 (tile.Transmitter // mekanism.common.block.BlockTransmitter // mekanism:transmitter)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (523,4,-67), Chunk: (at 11,0,13 in 32,-5; contains blocks 512,0,-80 to 527,255,-65), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Actual block type: ID #364 (tile.Transmitter // mekanism.common.block.BlockTransmitter // mekanism:transmitter)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [GCEntityPlayerMP['Eragon1997'/3, l='New World', x=523.58, y=4.00, z=-68.49]]
	Chunk stats: ServerChunkCache: 289 Drop: 0
	Level seed: -3045288156970664845
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (520,4,-71), Chunk: (at 8,0,9 in 32,-5; contains blocks 512,0,-80 to 527,255,-65), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 612 game time, 612 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 64849 (now: false), thunder time: 175139 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3773191632 bytes (3598 MB) / 5100273664 bytes (4864 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version          | Source                                  | Signature                                |
	|:------ |:------------------- |:---------------- |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2           | minecraft.jar                           | None                                     |
	| LCHIJA | mcp                 | 9.42             | minecraft.jar                           | None                                     |
	| LCHIJA | FML                 | 8.0.99.99        | forge-1.12.2-14.23.5.2860.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2860     | forge-1.12.2-14.23.5.2860.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       | 4.0.2.284        | minecraft.jar                           | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.284        | Galacticraft-1.12.2-4.0.2.284.jar       | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.284        | Galacticraft-1.12.2-4.0.2.284.jar       | None                                     |
	| LCHIJA | mekanism            | 1.12.2-9.8.3.390 | Mekanism-1.12.2-9.8.3.390.jar           | None                                     |
	| LCHIJA | mekanismgenerators  | 1.12.2-9.8.3.390 | MekanismGenerators-1.12.2-9.8.3.390.jar | None                                     |
	| LCHIJA | mekanismtools       | 1.12.2-9.8.3.390 | MekanismTools-1.12.2-9.8.3.390.jar      | None                                     |

	Loaded coremods (and transformers): 
MicdoodlePlugin (Galacticraft-1.12.2-4.0.2.284.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['Eragon1997'/3, l='New World', x=523.58, y=4.00, z=-68.49]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
