### ISSUE TITLE
Add the altitude at which the rocket leaves the dimension

### ISSUE THREAD

**Issue by sddsd2332** [TeamGalacticraft/Galacticraft-Legacy#51]
### Forge Version

14.23.5.2854

### Galacticraft Version

4.0.281

### Log or Crash Report

 N/A

### Reproduction steps

My English is not very good, so this is translated by Google.
it's not a bug
just a suggestion
I want to control the rocket to leave the current dimension when it reaches the specified height through configuration options, [because CubicChunks are installed, I set the height to 4096, but the rocket will leave the current dimension at 1200, so I want to request to modify the rocket transmission height distance ]:)

**Comment by ROMVoid95** [comment]
While GC itself sets this for each planet and moon it adds, as well as the overworld. All addons set and control that property for their own planets/moons/etc. And it could have a particular value set for a reason. Are you asking for this feature for the Overworld only or all planets/moons?

**Comment by sddsd2332** [comment]
What I want is to be able to control this function in the configuration files of all dimensions, which can be used as the altitude required to leave the atmosphere of different planets:)

**Comment by ROMVoid95** [comment]
Since that would require addon devs to also make that a configurable option, this is something I don't see as being done in this version of Galacticraft.

**Comment by sddsd2332** [comment]
Then I may need to build and modify it myself, sorry for your trouble
