### ISSUE TITLE
Aluminium cable error or redstone generator error?

### ISSUE THREAD

**Issue by FaithWillOutCome** [TeamGalacticraft/Galacticraft-Legacy#57]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.284

### Log or Crash Report

[crash-2022-03-11_22.28.21-server.txt](https://github.com/TeamGalacticraft/Galacticraft-Legacy/files/8235479/crash-2022-03-11_22.28.21-server.txt)

### Reproduction steps

I tried to carry gasoline from refinery to fuel loader. 
I placed buildcraft pipes from refienry to fueld loader and when i tried to place redstone generator directly to wooden liquid pipe game crashed and I cant open the save right now. Everytime im trying to get in to my world but it gaves me the same crash
It says: The game crashed whilst exception while updating neighbours
Error: java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.tile.TileEntityAluminumWire cannot be cast to buildcraft.api.mj.IMjReceiver
ExitCode: -1

i uploaded the crash report

**Comment by ROMVoid95** [comment]
@FaithWillOutCome is it possible you could share a screenshot of the setup you had that caused this crash? Wanted to make sure everything is covered in the fix before I push the changes.
