### ISSUE TITLE
Small quantities of copper generating in the overworld after setting "Enable Copper Ore Gen" to false

### ISSUE THREAD

**Issue by Roggnar** [TeamGalacticraft/Galacticraft-Legacy#58]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.284

### Reproduction steps

I used the digital miner from Mekanism to collect the ores.

1. Set "Enable Copper Ore Gen" to false in the config file and start your game
2. Create a new world
3. Config a digital miner to only collect copper ore from Galacticraft
4. The miner will collect 1 ore every couple chunks or so

(I don't have the problem with tin and I didn't try the other ores)

**Comment by ROMVoid95** [comment]
I cannot reproduce, tested in a new world, and right now on my 15th chunk and skipping around as well.
