### ISSUE TITLE
Server Crash with Mekanism

### ISSUE THREAD

**Issue by TheComputerizer** [TeamGalacticraft/Galacticraft-Legacy#63]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.284

### Log or Crash Report

[crash report](https://gist.github.com/TheComputerizer/a3c698fc508392ca704dfff927e6f1e3)

### Reproduction steps

Unsure. This became an issue after updating Galacticraft from 4.0.2.280.

I was pointed to [this line](https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityFluidPipe.java#L405) when I opened an issue on Mekanism

**Comment by tonimark** [comment]
i have the same problem when i loaded an old save , I needed to update from 4.0.2.280. to 4.0.2.284 in order for galaxy space update to work
