### ISSUE TITLE
Garden of Glass skybox is overlapping with this mod's Earth skybox, causing both to flicker.

### ISSUE THREAD

**Issue by MagmaBro123** [TeamGalacticraft/Galacticraft-Legacy#64]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.284

### Log or Crash Report

N/A

### Reproduction steps

Install this mod with its required mods, Garden of Glass, and Botania. Create a world using Garden of Glass's worldtype. This mod's Earth skybox shouldn't be active on this worldtype.

I'm not a YouTuber, but you'd see this flickering between the 2 skyboxes.
![2022-05-15_18 40 55_4](https://user-images.githubusercontent.com/51277766/168502543-b806951a-a9f4-46fc-81d8-c143b4c9a352.png)

**Comment by ROMVoid95** [comment]
Cannot reproduce running the latest versions of the other mods, in that world type.  So there must be more mods present that were not stated, that is all I can conclude with the info given. anything else that could maybe point to the reason can be provided and I'll check on it.

**Comment by MagmaBro123** [comment]
May be a graphics card issue, I'm confused.

![image](https://user-images.githubusercontent.com/51277766/168516820-cb195371-8e8e-4372-8d3f-c8bff4892cb4.png)
