### ISSUE TITLE
[Enhancement] Allow users to specify dimensions GC's atmospherics are used in

### ISSUE THREAD

**Issue by Deiwos** [TeamGalacticraft/Galacticraft-Legacy#65]
### Type

New

### Describe Your Request

Currently, the only dimensions that have GC's atmospheric system (aka requiring Galacticraft space suits and oxygen sealers to survive) are dimensions introduced by GC or GC addons. However, Advanced Rocketry is capable of both overriding GC's atmospheric system in GC dimensions and using the atmosphere system on other unrelated dimensions.

I would basically like GC to be able to do that itself, so the player would be able to specify dimensions in a config file to have the functionality work in so they require a space suit/oxygen sealing/etc. to survive in.

**Comment by ROMVoid95** [comment]
This would be something more suited for GC 5, Not something that would require a considerable amount of time and changing of the system in place now.
