### ISSUE TITLE
crash with wumple util & multiblocked

### ISSUE THREAD

**Issue by rebarakuk** [TeamGalacticraft/Galacticraft-Legacy#67]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.284

### Log or Crash Report

[crash report](https://gist.github.com/rebarakuk/781b6d97a99a8e8eba037b3291f88f97)

[latest log](https://gist.github.com/rebarakuk/fba1254f758fa72a73ffb59dcd1c517f)

### Reproduction steps

1. right click the blueprint table core in multiblocked
2. click anything on gui and it happens randomly or click and right click the chest in the gui

Wumple util library 2.12.9
Multiblocked 0.6.0

[Multiblocked on Curseforge](https://www.curseforge.com/minecraft/mc-mods/multiblocked)

**Comment by ROMVoid95** [comment]
Does this happen if GC is not installed? Having a hard time seeing where GC is to blame

**Comment by rebarakuk** [comment]
maybe other mod made this crash, I installed wumple, galacticraft, multiblocked only but no crash happened

**Comment by ROMVoid95** [comment]
alright then, going to close this since the provided information points to another mod causing the issue, feel free to reply if anymore information comes up that shows GC was indeed the issue and I'll reopen.
