### ISSUE TITLE
Request to make player inventory tabs an individual library mod

### ISSUE THREAD

**Issue by lcy0x1** [TeamGalacticraft/Galacticraft-Legacy#69]
### Type

Existing

### Describe Your Request

I find the player inventory tabs quite useful. Would you make this an individual library mod, or authorize me to use your code to make such library mod, so that more mods can utilize this feature?

I saw [custom NPC mod](https://www.curseforge.com/minecraft/mc-mods/custom-npcs) is already using it, and I would like to use this in my mod as well. (they are closed source so I use IDEA to decompile them, and I find they have a package called `micdoodle8.mods.galacticraft.api.client.tabs`)

If you don't want to make it a library, may I use this idea in my mod? I will write my own code and credit you for your idea. (my mods are on 1.18.2)

**Comment by ROMVoid95** [comment]
This is not something that would be beneficial for this version of the mod, As for the idea, since we can't own an idea for something I'd say sure :)
