### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaBro123** [TeamGalacticraft/Galacticraft-Legacy#74]
### Forge Version

14.23.5.2860

### Galacticraft Version

See screenshot in description.

### Log or Crash Report

No report is created. I can only give a log file.

[latest.log](https://github.com/TeamGalacticraft/Galacticraft-Legacy/files/9117336/latest.log)

### Reproduction steps

1. Start the game.
2. Crashes.

![image](https://user-images.githubusercontent.com/51277766/179140132-5f403656-fec4-4e1a-8971-ca3680cfaf45.png)

**Comment by ROMVoid95** [comment]
Galacticraft-Legacy is the 1.12.2 Galacticraft4 version and is only 1 jar for all 3 previously needed jar files

(GalacticraftCore, Galacticraft-Planets and MicdoodleCore)

If you are updating from a previous version (any below 4.0.2.280) you MUST remove the three old jar files from your mods folder

**Comment by MagmaBro123** [comment]
Ah. I'm stupid apparently. Why was the mod in multiple parts before, though?

**Comment by ROMVoid95** [comment]
> 

¯\_(ツ)_/¯
