### ISSUE TITLE
Game crashes when hit a Creeper Egg

### ISSUE THREAD

**Issue by QuantumStatement** [TeamGalacticraft/Galacticraft-Legacy#76]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.284

### Log or Crash Report

[Crash Report](https://gist.github.com/QuantumStatement/dd9405124b6b17a9cf52b88d5024d30f)

### Reproduction steps

1. Create new world in Creative mode
2. Place Creeper Egg
3. Change gamemode to Survival
4. Hit Creeper Egg

**Comment by ROMVoid95** [comment]
duplicate of #62
