### ISSUE TITLE
Crash with Oxygen Loader

### ISSUE THREAD

**Issue by knoxhack** [TeamGalacticraft/Galacticraft-Legacy#81]
### Forge Version

14.23.5.2860

### Galacticraft Version

Galacticraft-1.12.2-4.0.3

### Log or Crash Report

https://raw.githubusercontent.com/NFINIT-Development/Planetary/master/crash-2022-08-13_21.48.26-server.txt

### Reproduction steps

Place Oxygen loader next to launch pad
...

**Comment by knoxhack** [comment]
https://github.com/ReadOnlyDevelopment/SpaceCraftX-Reloaded/issues/6

**Comment by ROMVoid95** [comment]
closing since after a general glance it shows the root cause is the addon and not galacticraft itself. Will reopen this if this changes.
