### ISSUE TITLE
Server Crash When Entering Space with SpongeForge

### ISSUE THREAD

**Issue by spruill7716** [TeamGalacticraft/Galacticraft-Legacy#83]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.3

### Log or Crash Report

https://gist.github.com/spruill7716/564a99d28df5b7bd2ad250788776ad84

### Reproduction steps

Using the latest SpongeForge, I am unable to to enter the space/planet selection menu after launching a rocket. The server eventually times out after a while after not getting a response.

**Comment by ROMVoid95** [comment]
In your `server.properties` file, set `max-tick-time` to a higher value or `-1` to disable the server watchdog.
Example:
`max-tick-time=-1`
