### ISSUE TITLE
Causing crashes in the 1.12.2 pack

### ISSUE THREAD

**Issue by zephyr118** [TeamGalacticraft/Galacticraft-Legacy#85]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.3

### Log or Crash Report

https://mclo.gs/AdwV1dl

### Reproduction steps

1. I updated the 1.12.2 pack to the new 1.5.0 release and booted up the game. Using technic launcher.
2. After I logged out and tried launching the pack later it crahsed  while trying to launch and generated the attached log. The log is th esmae everytime i experience the crash.
3. If i remove the pack via the technic launcher and reinstall it it will owrk once but then crashes on any later attempts to launch the pack.

**Comment by xJon** [comment]
Found out this is due to BuildCraft (https://github.com/Pabilo8/ImmersiveIntelligence/issues/144#issuecomment-1051285353).

**Comment by xJon** [comment]
The issue prevails https://mclo.gs/FFTlSfh (after following the changes to BuildCraft).

**Comment by ACGaming** [comment]
https://github.com/TeamGalacticraft/Galacticraft-Legacy/pull/89

**Comment by Xeladin** [comment]
anyone found an easy fix?

**Comment by xJon** [comment]
@Xeladin This should be resolved now on the latest release.

**Comment by Xeladin** [comment]
> @Xeladin This should be resolved now on the latest release.

really?? from immersive engineering/technology/intelligence or from build craft?

**Comment by ROMVoid95** [comment]
Galacticraft 4.0.4
fix was commited [Here](https://github.com/TeamGalacticraft/Galacticraft-Legacy/commit/5cd1443f9f6bd5de3318bf955d4c645f101a29c)

**Comment by Xeladin** [comment]
> Galacticraft 4.0.4 fix was commited [Here](https://github.com/TeamGalacticraft/Galacticraft-Legacy/commit/5cd1443f9f6bd5de3318bf955d4c645f101a29c)

i...don't really understand but, thank you for informing.

**Comment by xJon** [comment]
@Xeladin The issue between BuildCraft and other mods (not Galacticraft) is not resolved and requires a workaround posted over [here](https://github.com/Pabilo8/ImmersiveIntelligence/issues/144#issuecomment-1051285353).

**Comment by Xeladin** [comment]
> @Xeladin The issue between BuildCraft and other mods (not Galacticraft) is not resolved and requires a workaround posted over [here](https://github.com/Pabilo8/ImmersiveIntelligence/issues/144#issuecomment-1051285353).

oh! so it is "fixable" momently. how would I be able to get into the buildcraft option? Im fresh new into java and server configurations. if you can help

**Comment by ACGaming** [comment]
That would be setting the value for `I:guideItemSearchLimit` to `1500` in `..\config\buildcraft\main.cfg` with a text editor of your choice.

**Comment by Xeladin** [comment]
OH MY GOD ITS FIXED!! THANK YOU SO MUCH!!!
