### ISSUE TITLE
IC2 Classic compatibility issues

### ISSUE THREAD

**Issue by xJon** [TeamGalacticraft/Galacticraft-Legacy#90]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.3

### Reproduction steps

First reported over https://github.com/TeamGalacticraft/Galacticraft-Legacy/issues/30#issuecomment-1193140906.
Install Galacticraft and IC2 Classic, then place an aluminum wire next to an IC2 Classic machine. It will not connect (unlike IC2 Experimental) and will lag the game.

**Comment by xJon** [comment]
Log error: https://mclo.gs/fAbQzYJ

**Comment by ACGaming** [comment]
EnergyUtil#getAdjacentPowerConnections is lacking additional checks for IC2 Classic because the checked methods `getSinkDirs` and `getSourceDirs` don‘t exist.

**Comment by xJon** [comment]
There is no longer a lag issue thanks to https://github.com/TeamGalacticraft/Galacticraft-Legacy/commit/71e006a39fbb7074e0a167930ea6c1ca571cfb4e.
