### ISSUE TITLE
I cant go to the moon

### ISSUE THREAD

**Issue by Ohookkk** [TeamGalacticraft/Galacticraft-Legacy#92]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.3

### Log or Crash Report

[2022-08-30-2.log](https://github.com/TeamGalacticraft/Galacticraft-Legacy/files/9451337/2022-08-30-2.log)

### Reproduction steps

1. I go to the space
2. I select the moon
3. The moon button is red and the tier is red
![image](https://user-images.githubusercontent.com/94994282/187394110-bfe0e69a-0b03-4969-945b-3f2fb45f8eef.png)

**Comment by ROMVoid95** [comment]
Fix the dimensionId `-30` conflict and check if the issue still persists.
