### ISSUE TITLE
Breaking or dropping items disappear when on the moon

### ISSUE THREAD

**Issue by orangechickhen** [TeamGalacticraft/Galacticraft-Legacy#96]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.2.280

### Log or Crash Report

Mod pack - Kealis Bombs Guns War V3.0.0

Multiplayer (MP) hosting own server

Issue - It seems that whenever a player goes to space, breaking blocks or dropping items causes them to disappear. Mobs also don't drop items when killed. Disconnecting and reconnecting does nothing however restarting the server fixes the issue. But of course, having to restart the server every time we go to the moon is a pain. Wondering if there's an incompatibility issue with another mod in the pack?

The Galacticraft was part of a mod pack that is no longer available online
I have the main game files and the server files in this google drive
Latest log and debug files are also located in this drive
[https://drive.google.com/drive/folders/1CAH1mDDuGzfWs-d1WjVbYKqEdo2U86j4?usp=sharing]

### Reproduction steps

1. Launch to the moon
2. after landing breaking a block with an impact drill from HBM's Nuclear Tech Mod
3. Blocks break but disappear
4. tried with other items like base Minecraft diamond pick but items disappear still
5. dropped items also disappear
6. killing mobs don't drop items
7. Issue persists after returning to earth
8. Disconnecting from server and reconnecting doesn't fix issue
9. restarting the server after players are on the moon fixes this
...

**Comment by ROMVoid95** [comment]
Testing in dev does not give the same results when using the drill stated, nor do any of the other issues present themselves. You can try and replicate this using the latest version.
