### ISSUE TITLE
Random user client side crashing on Tekkit 2 Server

### ISSUE THREAD

**Issue by SparksSkywere** [TeamGalacticraft/Galacticraft-Legacy#98]
### Forge Version

14.23.5.2860

### Galacticraft Version

4.0.3-Tekkit-2-Build

### Log or Crash Report

This is listed from another ticket I am with on Tekkit 2: https://github.com/xJon/Tekkit-2/issues/69

"So a day of testing with lots of ideas and going through many things, we have found some culprits to the issue

Player models are spawned multiple times and classed as "Unknown" which causes the crashes, such as the one provided by a player: Retry entities: 3 total; [EntityLatchedRenderer['unknown'/2101909, l='MpServer', x=-1.76, y=64.00, z=0.48], EntityLatchedRenderer['unknown'/2106662, l='MpServer', x=-142.67, y=67.00, z=486.75], GCEntityOtherPlayerMP['blikakis'/40366, l='MpServer', x=-142.67, y=67.00, z=486.75]]

We located the entity and could not remove it, though a reload of the server will clear all these entities, we tested to see about unloading and reloading of chunks when these happen, to which yes, when a chunk is reloaded and this missing entity is detected it will cause a crash.

I have attempted to load in many cleanup tools to stop the crashes, a plugin called CatLagClear managed to help but this cleaned up the server every 10 mins, not exactly the best because I have to use a plugin loader called Sponge so this makes me instantly in the fault as it is not what you originally made for the server, but I am trying many ideas.

So something is causing these creations of entities when players disconnect from the server and well clients are not cleaning up the players, this is theoretically what I see causing the issue but cannot pinpoint the crashes just yet, we will keep looking into this to find the issue, we are also removing and adding mods on clients to help."

We have already tested disabling "enableLatchedRendererSpawn" in "ichunutil.cfg" but no luck, xJon suggested it could be "GCEntitiyOtherPlayerMP"?

Tekkit 2 Crashes with logs, collected a lot!

Had others crash, their logs are:
https://mclo.gs/5BGP1dn
https://mclo.gs/OcWwrYn
https://mclo.gs/SPCcMOh
https://mclo.gs/3p4ZQzO
https://mclo.gs/m5ZWy3p
https://mclo.gs/1tVR0yG
https://mclo.gs/a4b3kUi
https://mclo.gs/2CcTLCz
https://mclo.gs/FjIEff9
https://mclo.gs/Ly0y7U9
https://mclo.gs/Mra84MR
https://mclo.gs/27jidA0

My logs:
https://mclo.gs/bx97kWM
https://mclo.gs/yD2d4Lv
https://mclo.gs/yWzcKC8
https://mclo.gs/FlrXYdn

### Reproduction steps

1. Do this
2. Do that
3. Crash/Bug
...
1. Join a Tekkit 2 server, have around 20 players
2. Play for over a week continiously and slowly overtime as players went around planets it started happening
3. It just crashes at random times, though the same or similar errors occur, I cannot explain it fully but if you wish to join the server to experience it yourself you may.

**Comment by ROMVoid95** [comment]
Can we check if the issue here is still present with the latest release?
